ERPMVC/Models/Inventarios/SolicitudCertificadoDeposito.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ERPMVC.Models
{
    public class SolicitudCertificadoDeposito
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Id")]
        public Int64 IdSCD { get; set; }
        [Display(Name = "No de solicitud")]
        public Int64 NoCD { get; set; }
        [Display(Name = "Cliente")]
        public Int64 CustomerId { get; set; }

        [Display(Name = "Cliente")]
        public string CustomerName { get; set; }

        [Display(Name = "Bodega")]
        public Int64 WarehouseId { get; set; }
        [Display(Name = "Bodega")]
        public string WarehouseName { get; set; }

        [Display(Name = "Tipo Servicio")]
        public Int64 ServicioId { get; set; }

        [Display(Name = "Servicio")]
        public string ServicioName { get; set; }

        [Display(Name = "Dirección")]
        public string Direccion { get; set; }
        [Display(Name = "Fecha de certificado")]
        public DateTime FechaCertificado { get; set; }

        [Display(Name = "Empresa")]
        public string NombreEmpresa { get; set; }

        public Int64 IdEstado { get; set; }
        public string Estado { get; set; }

        [Display(Name = "Seguro")]
        public string EmpresaSeguro { get; set; }

        [Display(Name = "No. Poliza")]
        public string NoPoliza { get; set; }
        [Display(Name = "Sujetos a pago")]
        public double SujetasAPago { get; set; }
        [Display(Name = "Fecha de vencimiento")]
        public DateTime FechaVencimientoDeposito { get; set; }

        [Display(Name = "Número de traslado")]
        public Int64 NoTraslado { get; set; }

        [Display(Name = "Fecha de vencimiento")]
        public DateTime FechaVencimiento { get; set; }

        [Display(Name = "Aduana")]
        public string Aduana { get; set; }

        [Display(Name = "Carta de porte o manifiesto No.")]
        public string ManifiestoNo { get; set; }

        [Display(Name = "Almacenaje")]
        public string Almacenaje { get; set; }
        [Display(Name = "Seguro")]
        public string Seguro { get; set; }

        [Display(Name = "Otros Cargos")]
        public string OtrosCargos { get; set; }

        [Display(Name = "Banco")]
        public Int64 BankId { get; set; }
        [Display(Name = "Banco")]
        public string BankName { get; set; }
        [Display(Name = "Moneda")]
        public Int64 CurrencyId { get; set; }
        [Display(Name = "Moneda")]
        public string CurrencyName { get; set; }
        [Display(Name = "Monto de garantia")]
        public double MontoGarantia { get; set; }
        [Display(Name = "Fecha pago")]
        public DateTime FechaPagoBanco { get; set; }

        [Display(Name = "Porcentaje intereses")]
        public double PorcentajeInteresesInsolutos { get; set; }

        [Display(Name = "Fecha de inicio")]
        public DateTime FechaInicioComputo { get; set; }

        [Display(Name = "Lugar de firma")]
        public string LugarFirma { get; set; }

        [Display(Name = "Fecha de firma")]
        public DateTime FechaFirma { get; set; }

        [Display(Name = "Nombre prestatario")]
        public string NombrePrestatario { get; set; }


        /// <summary>
        /// Totales de Detalle de Linea
        /// </summary>
        [Display(Name = "Suma Cantidad")]
        public double Quantitysum { get; set; }

        [Display(Name = "Total")]
        public double Total { get; set; }

        /// <summary>
        /// Totales de Detalle de Linea
        /// </summary>


        public DateTime FechaCreacion { get; set; }
        public DateTime FechaModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }

        public List<SolicitudCertificadoLine> _SolicitudCertificadoLine { get; set; } = new List<SolicitudCertificadoLine>();
    }






}

ERPMVC/Controllers/Inventarios/SolicitudCertificadoDepositoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ERPMVC.Helpers;
using ERPMVC.Models;
using ERPMVC.DTO;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Syncfusion.ReportWriter;
using Syncfusion.Report;
using Syncfusion.Pdf;
using Syncfusion.DocIORenderer;

namespace ERPMVC.Controllers
{
    [Authorize]
    [CustomAuthorization]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class SolicitudCertificadoDepositoController : Controller
    {
        private readonly IOptions<MyConfig> config;
        private readonly ILogger _logger;
        private readonly IHostingEnvironment _hostingEnvironment;
        public SolicitudCertificadoDepositoController(ILogger<SolicitudCertificadoDepositoController> logger, IOptions<MyConfig> config, IHostingEnvironment hostingEnvironment)
        {
            this.config = config;
            this._logger = logger;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("[action]")]
        public async Task<ActionResult> pvwSolicitudCertificadoDeposito([FromBody]DTO.SolicitudCertificadoDepositoDTO _SolicitidCertificadoDeposito)
        {
            //DTO.SolicitudCertificadoDepositoDTO _SolicitudCertificadoDeposito = new DTO.SolicitudCertificadoDepositoDTO();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/SolicitudCertificadoDeposito/GetSolicitudCertificadoDepositoById/" + _SolicitidCertificadoDeposito.IdSCD);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _SolicitidCertificadoDeposito = JsonConvert.DeserializeObject<DTO.SolicitudCertificadoDepositoDTO>(valorrespuesta);

                }

                if (_SolicitidCertificadoDeposito == null)
                {
                    _SolicitidCertificadoDeposito = new DTO.SolicitudCertificadoDepositoDTO
                    {
                        IdSCD = 0,
                        FechaCertificado = DateTime.Now,
                        FechaVencimiento = DateTime.Now.AddDays(60),
                        FechaVencimientoDeposito = DateTime.Now.AddDays(30),
                        FechaFirma = DateTime.Now,
                        FechaInicioComputo = DateTime.Now,
                        FechaPagoBanco = DateTime.Now,

                    };
                }else {
                    _SolicitidCertificadoDeposito.editar = 0;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }



            return PartialView(_SolicitidCertificadoDeposito);

        }


        [HttpGet]
        public async Task<DataSourceResult> Get([DataSourceRequest]DataSourceRequest request)
        {
            List<SolicitudCertificadoDeposito> _SolicitudCertificadoDeposito = new List<SolicitudCertificadoDeposito>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/SolicitudCertificadoDeposito/GetSolicitudCertificadoDeposito");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _SolicitudCertificadoDeposito = JsonConvert.DeserializeObject<List<SolicitudCertificadoDeposito>>(valorrespuesta);

                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return _SolicitudCertificadoDeposito.ToDataSourceResult(request);

        }

        [HttpPost("[action]")]
        public async Task<ActionResult<SolicitudCertificadoDeposito>> SaveSolicitudCertificadoDeposito([FromBody]DTO.SolicitudCertificadoDepositoDTO _SolicitudCertificadoDepositoP)
        {
            SolicitudCertificadoDeposito _SolicitudCertificadoDeposito = _SolicitudCertificadoDepositoP;
            try
            {
                //SolicitudCertificadoDeposito _listSolicitudCertificadoDeposito = new SolicitudCertificadoDeposito();
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/SolicitudCertificadoDeposito/GetSolicitudCertificadoDepositoById/" + _SolicitudCertificadoDeposito.IdSCD);
                string valorrespuesta = "";
                _SolicitudCertificadoDeposito.FechaModificacion = DateTime.Now;
                _SolicitudCertificadoDeposito.UsuarioModificacion = HttpContext.Session.GetString("user");
                if (result.IsSuccessStatusCode)
                {

                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _SolicitudCertificadoDeposito = JsonConvert.DeserializeObject<SolicitudCertificadoDeposito>(valorrespuesta);
                }

                if (_SolicitudCertificadoDepositoP.IdSCD == 0)
                {
                    _SolicitudCertificadoDeposito.FechaCreacion = DateTime.Now;
                    _SolicitudCertificadoDeposito.UsuarioCreacion = HttpContext.Session.GetString("user");
                    var insertresult = await Insert(_SolicitudCertificadoDepositoP);
                }
                else
                {
                    var updateresult = await Update(_SolicitudCertificadoDeposito.IdSCD, _SolicitudCertificadoDepositoP);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }

            return Json(_SolicitudCertificadoDeposito);
        }

        // POST: SolicitudCertificadoDeposito/Insert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<SolicitudCertificadoDeposito>> Insert(SolicitudCertificadoDeposito _SolicitudCertificadoDeposito)
        {
            try
            {
                // TODO: Add insert logic here
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                _SolicitudCertificadoDeposito.UsuarioCreacion = HttpContext.Session.GetString("user");
                _SolicitudCertificadoDeposito.UsuarioModificacion = HttpContext.Session.GetString("user");
                var result = await _client.PostAsJsonAsync(baseadress + "api/SolicitudCertificadoDeposito/Insert", _SolicitudCertificadoDeposito);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _SolicitudCertificadoDeposito = JsonConvert.DeserializeObject<SolicitudCertificadoDeposito>(valorrespuesta);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                return BadRequest($"Ocurrio un error{ex.Message}");
            }
            return Ok(_SolicitudCertificadoDeposito);
            // return new ObjectResult(new DataSourceResult { Data = new[] { _SolicitudCertificadoDeposito }, Total = 1 });
        }

        [HttpPut("{id}")]
        public async Task<ActionResult<SolicitudCertificadoDeposito>> Update(Int64 id, SolicitudCertificadoDeposito _SolicitudCertificadoDeposito)
        {
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));

                var result = await _client.PutAsJsonAsync(baseadress + "api/SolicitudCertificadoDeposito/Update", _SolicitudCertificadoDeposito);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _SolicitudCertificadoDeposito = JsonConvert.DeserializeObject<SolicitudCertificadoDeposito>(valorrespuesta);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                return BadRequest($"Ocurrio un error{ex.Message}");
            }

            return new ObjectResult(new DataSourceResult { Data = new[] { _SolicitudCertificadoDeposito }, Total = 1 });
        }

        [HttpPost("[action]")]

ERPMVC/Views/SolicitudCertificadoDeposito/Index.cshtml
<script>


    function clearsession() {
            var dataObject = ["listadoproductoscertificadodeposito"];
         $.ajax({
            url: '@Url.Action("ClearSession","Common")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                  //  $('#myModalSalesOrder').modal('show');
            },
             error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert(textStatus + ": " + XMLHttpRequest.responseText);
              }
         });
    }

    function AddSolicitudCertificadoDeposito() {
       // $('#myModalSalesOrder').find(':input').not(':submit').val('');
         //$('#myModalSalesOrder').modal('show');

         clearsession();

         var dataObject = {
            IdSCD: 0,
            editar : 1
        };

        $.ajax({
            url: '@Url.Action("pvwSolicitudCertificadoDeposito", "SolicitudCertificadoDeposito")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                $("#salesorder").html('');
                $("#salesorder").html(result);

                //RefreshCertificadoDepositoDetail();
                 $("#btnSaveCotizacion").show();
                $('#myModalSolicitudCertificadoDeposito').modal('show');
            },
             error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert(textStatus + ": " + XMLHttpRequest.responseText);
              }
        });


    }

    function EditCertificadoDeposito(e) {
         e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dataObject = {
            IdSCD: dataItem.IdSCD,
            editar : 0
        };

        clearsession();

        $.ajax({
            url: '@Url.Action("pvwSolicitudCertificadoDeposito", "SolicitudCertificadoDeposito")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                $("#salesorder").html('');
                $("#salesorder").html(result);

              //  RefreshCotizacionesDetail();
                 $("#btnSaveCotizacion").hide();
                $('#myModalSolicitudCertificadoDeposito').modal('show');
            },
             error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert(textStatus + ": " + XMLHttpRequest.responseText);
              }
        });
    }

    function ImprimirCertificadoDeposito(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));


        window.location.href =  '@Url.Action("SFCertificadoDeposito", "CertificadoDeposito")/' + dataItem.SalesOrderId;




    }


    function closecondition() {
        $('#myModalConditions').modal('hide');
    }


</script>

<h3 class="text-themecolor">Solicitud Certificado de depósito</h3>

@(Html.Kendo().Grid<ERPMVC.Models.SolicitudCertificadoDeposito>()
                              .Name("gridSolicitudCertificadoDeposito")
                              .Columns(columns =>
                              {
                                  columns.Command(command =>
                                  {
                                      command.Custom("Editar").Text(" ").IconClass("fa fa-edit").Click("EditCertificadoDeposito");
                                      command.Custom("Imprimir").Text(" ").IconClass("fa fa-print").Click("ImprimirCertificadoDeposito");
                          //  command.Edit(); command.Destroy();
                      }).Width(250);

                                  columns.Bound(p => p.IdSCD).Title("Id").Width(150);
                                  columns.Bound(p => p.FechaCertificado).Format("{0:dd/MM/yyyy}").Title("Fecha Certificado").Width(150);
                                  columns.Bound(p => p.FechaVencimiento).Format("{0:dd/MM/yyyy}").Title("Fecha de Vencimiento").Width(150);
                                  columns.Bound(p => p.CustomerName).Title("Cliente").Width(150);
                                  columns.Bound(p => p.ServicioName).Title("Servicio").Width(150);
                                  columns.Bound(p => p.WarehouseName).Title("Sucursal").Width(150);
                                  columns.Bound(p => p.NombreEmpresa).Title("Nombre empresa").Width(150);
                                  columns.Bound(p => p.NoPoliza).Title("NoPoliza").Width(150);

                      //columns.Bound(p => p.Total).Title("Total").Width(150);
                  })
                                  .Filterable(f => f.Operators(o => o.ForString(s => s
                                           .Clear()
                                           .Contains("Contiene")
                                           .DoesNotContain("No contiene")
                                           .EndsWith("Termina con")
                                           .IsEqualTo("Es igual a")
                                           .IsNotEqualTo("No es igual a")
                                           .IsNull("Es nulo")
                                           .StartsWith("Inicia con")


                                     )
                                     .ForNumber(n => n
                                       .Clear()
                                       .IsEqualTo("Es igual a")
                                       .IsGreaterThan("Es mayor que")
                                       .IsLessThan("Es menor que")
                                       .IsNull("Es nulo")
                                       .IsLessThanOrEqualTo("Es menor o igual que")
                                       .IsGreaterThanOrEqualTo("Es mayor o igual que")
                                     )
                                     .ForDate(d => d
                                     .Clear()
                                     .IsEqualTo("Es igual que")
                                     .IsGreaterThan("Es mayor que")
                                     .IsLessThan("Es menor que")
                                     .IsLessThanOrEqualTo("Es menor o igual que")
                                     .IsGreaterThanOrEqualTo("Es mayor o igual que")
                                     .IsNotEqualTo("No es igual que")
                                      )
                                   ))
                              .ToolBar(tools =>
                              {
                      // tools.Create();
                      tools.Custom().Text("Agregar").IconClass("k-icon k-i-plus")
                                 .HtmlAttributes(new { @class = "k-i-plus-sm", onclick = "AddSolicitudCertificadoDeposito();" });

                                  tools.Excel().HtmlAttributes(new { @class = "toolbar-field" });
                                  tools.Pdf().HtmlAttributes(new { @class = "toolbar-field" });


                              })
                               .Editable(e => e.Mode(GridEditMode.PopUp))
                                .Sortable()
                                .AutoBind(true)
                                .Pageable()
                                .Filterable()
                                .Scrollable()
                                // .ClientDetailTemplateId("template")
                                .Pdf(pdf => pdf.FileName("CertificadoDepositoReport" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
                                + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".pdf")
                                .ProxyURL(Url.Action("Export", "Home")).AllPages())
                                  .Excel(excel => excel.FileName("CertificadoDepositoReport_" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
                                + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".xlsx").Filterable(true)
                                .ProxyURL(Url.Action("Export", "Home")).AllPages(true))
                                //.Events(e=>e.Save("onsave"))
                                .DataSource(dataSource =>

                               dataSource
                               //.Ajax()
                               .WebApi()
                                .ServerOperation(true)
                                .Model(model =>
                                {
                                    model.Id(p => p.IdSCD);
                                    model.Field(p => p.IdSCD).Editable(true);
                                    model.Field(p => p.IdSCD).Editable(true);


                                })
                                .Events(events =>
                                {
                                    events.Error("error_handler");
                        //events.upda("EditHandler");

                    })
                                .Read(read => read.Action("Get", "SolicitudCertificadoDeposito"))
                                .Create(create => create.Action("Insert", "CertificadoDeposito"))
                                .Update(update => update.Action("Update", "CertificadoDeposito", new { id = "{0}" }))
                                .Destroy(destroy => destroy.Action("Delete", "CertificadoDeposito", new { id = "{0}" }))
                          )
)

<div id="salesorder">
    @await Html.PartialAsync("pvwSolicitudCertificadoDeposito", new ERPMVC.DTO.SolicitudCertificadoDepositoDTO { IdSCD = 0, FechaCertificado = DateTime.Now, FechaVencimiento = DateTime.Now.AddDays(60)
     , FechaVencimientoDeposito =DateTime.Now.AddDays(30) ,FechaFirma = DateTime.Now,  FechaInicioComputo=DateTime.Now, FechaPagoBanco=DateTime.Now })
</div>





<div id="ConditionView">
    @*  @await Html.PartialAsync("~/Views/Conditions/pvwConditions.cshtml", new ERPMVC.Models.Conditions { ConditionId = 0 });*@
</div>

<div id="CustomerConditionView">
</div>

ERPMVC/Views/SolicitudCertificadoDeposito/SFSolicitudCertificadoDeposito.cshtml
@model ERPMVC.DTO.SolicitudCertificadoDepositoDTO

@using Syncfusion.JavaScript

<title>
    Solicitud de Certificado de Depósito
</title>
<div style=" align-items:center; height:825px;width: 100%;">
    <ej-report-viewer id="reportviewer1" rendering-begin="renderingBegin" locale="es-ES" processing-mode="Remote" ajax-before-load="ajaxBeforeLoad" report-service-url="/ReportViewer"  report-loaded="onReportLoaded" report-path="/ReportsTemplate/SolicitudCertificadoDeposito.rdl" />
</div>


<script type="text/javascript">

    function ajaxBeforeLoad(event) {
        var parameters = [{
            name: 'NoCD',
            labels: ['@Model.NoCD'],
            values: [@Model.NoCD],
            nullable: false
        }
        ];
        event.data = parameters;
    }; 

    function onReportLoaded(sender) {
        $("#reportviewer1_viewReportClick").val("Ver Reporte");
        var reportObj = $('#reportviewer1').data("ejReportViewer");
        reportObj.model.parameters = [{
            name: 'NoCD',
            labels: ['@Model.NoCD'],
            values: ['@Model.NoCD'],
            nullable: false
        }
        ];
    }

</script>


<ej-script-manager></ej-script-manager>

ERPMVC/Views/SolicitudCertificadoDeposito/SFSolicitudesEmitidasDetallado.cshtml
@model ERPMVC.DTO.CertificadoDepositoDTO

@{
    ViewData["Title"] = "Reporte Solicitudes Emitidas Detallado";
}


    @using Syncfusion.JavaScript

        <div style=" align-items:center; height:825px;width: 100%;">
                <ej-report-viewer id="reportviewer1" rendering-begin="renderingBegin" report-print="onPrintReport"  
                processing-mode="Remote" report-service-url="/ReportViewer"  
                      report-path="/ReportsTemplate/SolicitudesEmitidasDetallado.rdl" />
            </div>


            <script type="text/javascript">


                function onPrintReport(args) {
                    args.isStyleLoad = false;
                    var data = $("#reportviewer1").data('ejReportViewer');
                    if (data._browserInfo.name != "msie") {
                        args.printWind.printDelay = 2000 * data._pageModel.TotalPages;
                    }
                }

            </script>


            <ej-script-manager></ej-script-manager>