ERPMVC/Models/RRHH/PlanillaTipo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;




namespace ERPMVC.Models
{
    public class PlanillaTipo
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Id")]
        public long IdTipoPlanilla { get; set; }
        [Display(Name = "Tipo de Planilla")]
        public string TipoPlanilla { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Display(Name = "Estado")]
        public long EstadoId { get; set; }
        [Display(Name = "Categoria")]
        public long CategoriaId { get; set; }

        public Estados Estado { get; set; }

        public CategoriaPlanilla Categoria { get; set; }

        [Display(Name = "Usuario de creación")]
        public string Usuariocreacion { get; set; }
        [Display(Name = "Usuario de modificación")]
        public string Usuariomodificacion { get; set; }
        [Display(Name = "Fecha de creación")]
        public DateTime? FechaCreacion { get; set; }
        [Display(Name = "Fecha de modificación")]
        public DateTime? FechaModificacion { get; set; }
    }
}

ERPMVC/Models/RRHH/TipoPlanillas.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;




namespace ERPMVC.Models
{
    public class TipoPlanillas
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Id")]
        public long IdTipoPlanilla { get; set; }
        [Display(Name = "Tipo de Planilla")]
        public string TipoPlanilla { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Display(Name = "Estado")]
        public long EstadoId { get; set; }
        [Display(Name = "Categoria")]
        public long CategoriaId { get; set; }

        public Estados Estado { get; set; }

        public CategoriaPlanilla Categoria { get; set; }

        [Display(Name = "Usuario de creación")]
        public string Usuariocreacion { get; set; }
        [Display(Name = "Usuario de modificación")]
        public string Usuariomodificacion { get; set; }
        [Display(Name = "Fecha de creación")]
        public DateTime? FechaCreacion { get; set; }
        [Display(Name = "Fecha de modificación")]
        public DateTime? FechaModificacion { get; set; }
    }
}

ERPMVC/Controllers/RRHH/TipoPlanillasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ERPMVC.Helpers;
using ERPMVC.Models;
using ERPMVC.DTO;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Security.Claims;

namespace ERPMVC.Controllers
{
    [Authorize]
    [CustomAuthorization]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class PlanillaTiposController : Controller
    {
        private readonly IOptions<MyConfig> config;
        private readonly ILogger _logger;
        private readonly ClaimsPrincipal _principal;
        public PlanillaTiposController(ILogger<PlanillaTiposController> logger, IOptions<MyConfig> config, IHttpContextAccessor httpContextAccessor)
        {
            this.config = config;
            this._logger = logger;
            _principal = httpContextAccessor.HttpContext.User;
        }

        // GET: Customer
        //[Authorize(Policy = "RRHH.Parametros Tipo de Planilla")]
        public ActionResult PlanillaTipos()
        {
            ViewData["permisos"] = _principal;
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> Get([DataSourceRequest]DataSourceRequest request)
        {
            List<PlanillaTipo> _PlanillaTipos = new List<PlanillaTipo>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanillaTipos");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<List<PlanillaTipo>>(valorrespuesta);
                    _PlanillaTipos = _PlanillaTipos.OrderByDescending(p => p.IdTipoPlanilla).ToList();
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return Json(_PlanillaTipos.ToDataSourceResult(request));

        }

        [HttpGet]
        public async Task<JsonResult> GetPlanillaTipos([DataSourceRequest]DataSourceRequest request)
        {
            List<PlanillaTipo> _PlanillaTipos = new List<PlanillaTipo>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanillaTipos");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<List<PlanillaTipo>>(valorrespuesta);
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return Json(_PlanillaTipos.ToDataSourceResult(request));

        }


        [HttpGet]
        public async Task<JsonResult> GetPlanillaTiposActivo([DataSourceRequest] DataSourceRequest request)
        {
            List<PlanillaTipo> _PlanillaTipos = new List<PlanillaTipo>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanillaTipos");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<List<PlanillaTipo>>(valorrespuesta);
                    _PlanillaTipos = _PlanillaTipos.Where(e => e.EstadoId ==1).ToList();
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: {ex.ToString()}");
                throw ex;
            }


            return Json(_PlanillaTipos.ToDataSourceResult(request));

        }
        //--------------------------------------------------------------------------------------
        [HttpGet]
        public async Task<JsonResult> GetBOX([DataSourceRequest]DataSourceRequest request)
        {
            List<PlanillaTipo> _PlanillaTipos = new List<PlanillaTipo>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanilla");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<List<PlanillaTipo>>(valorrespuesta);

                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return Json(_PlanillaTipos);

        }

        [HttpPost("[action]")]
        public async Task<ActionResult> pvwAddPlanillaTipos([FromBody]PlanillaTipo _sarpara)
        {
            PlanillaTipo _PlanillaTipos = new PlanillaTipo();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanillaTiposById/" + _sarpara.IdTipoPlanilla);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<PlanillaTipo>(valorrespuesta);

                }

                if (_PlanillaTipos == null)
                {
                    _PlanillaTipos = new PlanillaTipo();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }



            return PartialView(_PlanillaTipos);

        }

        
        [HttpPost]
        public async Task<ActionResult<PlanillaTipo>> SavePlanillaTipos([FromBody]PlanillaTipo _PlanillaTiposP)
        {

            PlanillaTipo _PlanillaTipos = _PlanillaTiposP;
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/PlanillaTipos/GetPlanillaTiposById/" + _PlanillaTipos.IdTipoPlanilla);
                string valorrespuesta = "";
                _PlanillaTipos.FechaModificacion = DateTime.Now;
                _PlanillaTipos.Usuariomodificacion = HttpContext.Session.GetString("user");
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _PlanillaTipos = JsonConvert.DeserializeObject<PlanillaTipo>(valorrespuesta);
                }

                if (_PlanillaTipos == null)
                {
                    _PlanillaTipos = new Models.PlanillaTipo();
                }

                if (_PlanillaTiposP.IdTipoPlanilla == 0)
                {
                    _PlanillaTipos.FechaCreacion = DateTime.Now;
                    _PlanillaTipos.Usuariomodificacion = HttpContext.Session.GetString("user");
                    var ValidacionTipoPlanillaresult = await ValidacionPlanillaTipos(_PlanillaTiposP);
                    if ((ValidacionTipoPlanillaresult as ObjectResult).Value.ToString() == "Ya exíste un Tipo de Planilla creada con el mismo Nombre.")
                    {
                        return await Task.Run(() => BadRequest("Ya exíste un Tipo de Planilla creada con el mismo Nombre."));
                    }
                    var insertresult = await Insert(_PlanillaTiposP);
                }
                else
                {
                    _PlanillaTiposP.Usuariocreacion = _PlanillaTipos.Usuariocreacion;
                    _PlanillaTiposP.FechaCreacion = _PlanillaTipos.FechaCreacion;
                    var ValidacionTipoPlanillaresult = await ValidacionPlanillaTipos(_PlanillaTiposP);
                    if ((ValidacionTipoPlanillaresult as ObjectResult).Value.ToString() == "Ya exíste un Tipo de Planilla creada con el mismo Nombre.")
                    {

ERPMVC/Views/PlanillaTipos/PlanillaTipos.cshtml
@using Kendo.Mvc.UI
@using System.Security.Claims
@{
    ViewData["Title"] = "Tipo Planillas";
    ClaimsPrincipal permisos = (ClaimsPrincipal)ViewData["permisos"];
}

<script>

    function onsave(e) {
        //   console.log(new Date(e.model.FechaRecepcion).toISOString());
        // e.model.set('FechaRecepcion', new Date(e.model.FechaRecepcion).toISOString());
    }

    function caidata(data) {
        data.FechaRecepcion = data.FechaRecepcion.toISOString('yyyy-MM-dd');
        data.FechaLimiteEmision = data.FechaLimiteEmision.toISOString('yyyy-MM-dd');
    }

    function AddPlanillaTipos() {

        $('#ModalPlanillaTipos').find(':input').not(':submit').val('');
        $('#ModalPlanillaTipos').modal('show');
        $("#IdTipoPlanilla").val('0');
        $("#EstadoId").data('kendoDropDownList').value(0);



        var validator = $("#frmPlanillaTipos").data("kendoValidator");
        validator.hideMessages();
    }


    function EditPlanillaTipos(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dataObject = {
            IdTipoPlanilla: dataItem.IdTipoPlanilla,
            editar: 0
        };

        $.ajax({
            url: '@Url.Action("pvwAddPlanillaTipos", "PlanillaTipos")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                $("#numPlanillaTipos").html('');
                $("#numPlanillaTipos").html(result);


                //$("#btnCAI").hide();
                $('#ModalPlanillaTipos').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }

    function DeletePlanillaTipos(e) {
        if (confirm('¿Esta seguro que desea eliminar este registro?')) {
            e.preventDefault();
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            var dataObject = {
                IdTipoPlanilla: dataItem.IdTipoPlanilla
            };
            $.ajax({
                url: '@Url.Action("Delete", "PlanillaTipos")',
                method: 'POST',
                datatype: "json",
                contentType: 'application/json',
                async: false,
                data: JSON.stringify(dataObject),
                success: function (result) {
                    RefrescarGrid();
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                      $.toast({
                        heading: 'Error',
                        text:  XMLHttpRequest.responseJSON.Result,
                        position: 'top-right',
                        loaderBg: '#ff6849',
                        icon: 'error',
                        hideAfter: 30000,
                        stack: 6
                    });
                }
            });
        }
    }

    function RefrescarGrid() {
        var grid = $("#gridPlanillaTipos").getKendoGrid();
        grid.dataSource.read();
    }

    function EsGafi() {
        return { GAFI: false }
    }



</script>

<h3 class="text-themecolor">Tipo de Planillas</h3>

@(Html.Kendo().Grid<ERPMVC.Models.PlanillaTipo>
            ()

            .Name("gridPlanillaTipos")

            .Columns(columns =>
            {
                //if (permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Editar Tipo de Planilla", "true")
                //    || permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Eliminar Tipo de Planilla", "true"))
                //{
                columns.Command(command =>
                {
                    //command.Custom("Ver detalles").Click("Detalles");

                    //if (permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Editar Tipo de Planilla", "true"))
                    //{
                    command.Custom("Editar").Text(" ").IconClass("fa fa-edit").Click("EditPlanillaTipos");
                    //}
                    //if (permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Eliminar Tipo de Planilla", "true"))
                    //{
                    command.Custom("Eliminar").Text(" ").IconClass("fa fa-trash-alt").Click("DeletePlanillaTipos");
                    //}
                    //command.Destroy().Text(" ").IconClass("fa fa-trash-alt");
                }).Title("Acciones").Width(70);
            //}
                columns.Bound(p => p.IdTipoPlanilla).Width(150);
        columns.Bound(p => p.TipoPlanilla).Title("Nombre Tipo de Planillas").Width(170);
        columns.Bound(p => p.Descripcion).Title("Descripción").Width(170);
        columns.Bound(p => p.Estado.DescripcionEstado).Title("Estado").Width(170);


    })


            .ToolBar(tools =>
            {

        //tools.Create();
        //if (permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Agregar Tipo de Planilla", "true"))
        //{
        tools.Custom().Text("Agregar").IconClass("k-icon k-i-plus")
                                .HtmlAttributes(new { @class = "k-i-plus-sm", onclick = "AddPlanillaTipos()" });
        //}
        tools.Excel().Text("Exportar a excel").HtmlAttributes(new { @class = "toolbar-field" });
        tools.Pdf().Text("Exportar a pdf").HtmlAttributes(new { @class = "toolbar-field" });



    })
            .Editable(e => e.Mode(GridEditMode.PopUp))
            .Sortable()
            .Pageable(s => s
                .Messages(m => m.Display("Elementos mostrados {0} - {1} de {2}")
                .Empty("No hay datos."))
            )
            .Filterable()
            .Scrollable()
            .Pdf(pdf => pdf.FileName("Tipo_Planillas_Reporte" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".pdf")
            .ProxyURL(Url.Action("Export", "Home")).AllPages())
            .Excel(excel => excel.FileName("Tipo_Planillas_Reporte_" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".xlsx").Filterable(true)
            .ProxyURL(Url.Action("Export", "Home")).AllPages(true))
            .DataSource(dataSource =>
            dataSource
            .WebApi()

        .ServerOperation(true)
        .Model(model =>
        {
        model.Id(p => p.IdTipoPlanilla);
        model.Field(p => p.IdTipoPlanilla).Editable(false);


    })
            .Events(events => events.Error("error_handler"))
            .Read(read => read.Action("Get", "PlanillaTipos").Data("EsGafi"))
            .Create(create => create.Action("Insert", "PlanillaTipos").Type(HttpVerbs.Post))
            .Update(update => update.Action("Update", "PlanillaTipos").Type(HttpVerbs.Post))
            .Destroy(destroy => destroy.Action("Delete", "PlanillaTipos").Type(HttpVerbs.Post))

            )
            .Events(e =>
            {
        e.Save("onsave");

    })
)

<div id="numPlanillaTipos">
    @await Html.PartialAsync("pvwAddPlanillaTipos", new ERPMVC.Models.PlanillaTipo { IdTipoPlanilla = 0 })
</div>
<script>
    function setToolbarTooltip(btn_cl, btn_tooltip) {
        $("#gridPlanillaTipos").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    function setRowButtonTooltip(btn_cl, btn_tooltip) {
        $("#gridPlanillaTipos").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    setRowButtonTooltip(".k-grid-delete", "Eliminar registro");
    setRowButtonTooltip(".k-grid-Editar", "Editar registro");
    setRowButtonTooltip(".k-grid-Agregar", "Agregar nuevo registro");
</script>

ERPMVC/Views/PlanillaTipos/TipoPlanillas.cshtml
@using Kendo.Mvc.UI
@using System.Security.Claims
@{
    ViewData["Title"] = "Tipo Planillas";
    ClaimsPrincipal permisos = (ClaimsPrincipal)ViewData["permisos"];
}

<script>

    function onsave(e) {
        //   console.log(new Date(e.model.FechaRecepcion).toISOString());
        // e.model.set('FechaRecepcion', new Date(e.model.FechaRecepcion).toISOString());
    }

    function caidata(data) {
        data.FechaRecepcion = data.FechaRecepcion.toISOString('yyyy-MM-dd');
        data.FechaLimiteEmision = data.FechaLimiteEmision.toISOString('yyyy-MM-dd');
    }

    function AddTipoPlanillas() {

        $('#ModalTipoPlanillas').find(':input').not(':submit').val('');
        $('#ModalTipoPlanillas').modal('show');
        $("#IdTipoPlanilla").val('0');
        $("#EstadoId").data('kendoDropDownList').value(0);



        var validator = $("#frmTipoPlanillas").data("kendoValidator");
        validator.hideMessages();
    }


    function EditTipoPlanillas(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dataObject = {
            IdTipoPlanilla: dataItem.IdTipoPlanilla,
            editar: 0
        };

        $.ajax({
            url: '@Url.Action("pvwAddTipoPlanillas", "TipoPlanillas")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                $("#numTipoPlanillas").html('');
                $("#numTipoPlanillas").html(result);


                //$("#btnCAI").hide();
                $('#ModalTipoPlanillas').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }

    function DeleteTipoPlanillas(e) {
        if (confirm('¿Esta seguro que desea eliminar este registro?')) {
            e.preventDefault();
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            var dataObject = {
                IdTipoPlanilla: dataItem.IdTipoPlanilla
            };
            $.ajax({
                url: '@Url.Action("Delete", "TipoPlanillas")',
                method: 'POST',
                datatype: "json",
                contentType: 'application/json',
                async: false,
                data: JSON.stringify(dataObject),
                success: function (result) {
                    RefrescarGrid();
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                      $.toast({
                        heading: 'Error',
                        text:  XMLHttpRequest.responseJSON.Result,
                        position: 'top-right',
                        loaderBg: '#ff6849',
                        icon: 'error',
                        hideAfter: 30000,
                        stack: 6
                    });
                }
            });
        }
    }

    function RefrescarGrid() {
        var grid = $("#gridTipoPlanillas").getKendoGrid();
        grid.dataSource.read();
    }

    function EsGafi() {
        return { GAFI: false }
    }



</script>

<h3 class="text-themecolor">Tipo de Planillas</h3>

@(Html.Kendo().Grid<ERPMVC.Models.PlanillaTipo>
            ()

            .Name("gridTipoPlanillas")

            .Columns(columns =>
            {
                
                columns.Command(command =>
                {
                   
                    command.Custom("Editar").Text(" ").IconClass("fa fa-edit").Click("EditTipoPlanillas");
                    
                    command.Custom("Eliminar").Text(" ").IconClass("fa fa-trash-alt").Click("DeleteTipoPlanillas");
          
                }).Title("Acciones").Width(70);
            //}
                columns.Bound(p => p.IdTipoPlanilla).Width(150);
        columns.Bound(p => p.TipoPlanilla).Title("Nombre Tipo de Planillas").Width(170);
        columns.Bound(p => p.Descripcion).Title("Descripción").Width(170);
        columns.Bound(p => p.Estado.DescripcionEstado).Title("Estado").Width(170);


    })


            .ToolBar(tools =>
            {

        //tools.Create();
        //if (permisos.HasClaim("RRHH.Parametros Tipo de Planilla.Agregar Tipo de Planilla", "true"))
        //{
        tools.Custom().Text("Agregar").IconClass("k-icon k-i-plus")
                                .HtmlAttributes(new { @class = "k-i-plus-sm", onclick = "AddTipoPlanillas()" });
        //}
        tools.Excel().Text("Exportar a excel").HtmlAttributes(new { @class = "toolbar-field" });
        tools.Pdf().Text("Exportar a pdf").HtmlAttributes(new { @class = "toolbar-field" });



    })
            .Editable(e => e.Mode(GridEditMode.PopUp))
            .Sortable()
            .Pageable(s => s
                .Messages(m => m.Display("Elementos mostrados {0} - {1} de {2}")
                .Empty("No hay datos."))
            )
            .Filterable()
            .Scrollable()
            .Pdf(pdf => pdf.FileName("Tipo_Planillas_Reporte" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".pdf")
            .ProxyURL(Url.Action("Export", "Home")).AllPages())
            .Excel(excel => excel.FileName("Tipo_Planillas_Reporte_" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".xlsx").Filterable(true)
            .ProxyURL(Url.Action("Export", "Home")).AllPages(true))
            .DataSource(dataSource =>
            dataSource
            .WebApi()

        .ServerOperation(true)
        .Model(model =>
        {
        model.Id(p => p.IdTipoPlanilla);
        model.Field(p => p.IdTipoPlanilla).Editable(false);


    })
            .Events(events => events.Error("error_handler"))
            .Read(read => read.Action("Get", "TipoPlanillas").Data("EsGafi"))
            .Create(create => create.Action("Insert", "TipoPlanillas").Type(HttpVerbs.Post))
            .Update(update => update.Action("Update", "TipoPlanillas").Type(HttpVerbs.Post))
            .Destroy(destroy => destroy.Action("Delete", "TipoPlanillas").Type(HttpVerbs.Post))

            )
            .Events(e =>
            {
        e.Save("onsave");

    })
)

<div id="numTipoPlanillas">
    @await Html.PartialAsync("pvwAddTipoPlanillas", new ERPMVC.DTO.TipoPlanillasDTO { IdTipoPlanilla = 0 })
</div>
<script>
    function setToolbarTooltip(btn_cl, btn_tooltip) {
        $("#gridTipoPlanillas").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    function setRowButtonTooltip(btn_cl, btn_tooltip) {
        $("#gridTipoPlanillas").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    setRowButtonTooltip(".k-grid-delete", "Eliminar registro");
    setRowButtonTooltip(".k-grid-Editar", "Editar registro");
    setRowButtonTooltip(".k-grid-Agregar", "Agregar nuevo registro");
</script>