ERPMVC/Models/Contabilidad/Conciliacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ERPMVC.Models
{
    public class Conciliacion
    {
        [Display(Name = "Id")]
        public int ConciliacionId { get; set; }

        public Int64 BankId { get; set; }

        [Display(Name = "Id")]
        public Int64 AccountId { get; set; }

        [Required]
        [Display(Name = "BankName")]
        public string BankName { get; set; }

        [Display(Name = "Cuenta Bancaria")]
        public Int64 CheckAccountId { get; set; }

        [Required]
        [Display(Name = "FechaConciliacion")]
        public DateTime FechaConciliacion { get; set; }

        [Display(Name = "Fecha Inicio")]
        public DateTime DateBeginReconciled { get; set; }
        [Display(Name = "Fecha Fin")]
        public DateTime DateEndReconciled { get; set; }

        [Required]
        [Display(Name = "SaldoConciliado")]
        public Double SaldoConciliado { get; set; }


        public string Estado { get; set; }
        public Int64 EstadoId { get; set; }
        [ForeignKey("EstadoId")]
        public Estados Estados { get; set; }


        [Required]
        [Display(Name = "FechaCreacion")]
        public DateTime FechaCreacion { get; set; }

        [Required]
        [Display(Name = "FechaModificacion")]
        public DateTime FechaModificacion { get; set; }

        [Required]
        [Display(Name = "UsuarioCreacion")]
        public string UsuarioCreacion { get; set; }

        [Required]
        [Display(Name = "UsuarioModificacion")]
        public string UsuarioModificacion { get; set; }

        [Required]
        [Display(Name = "Saldo en Estado de Cuenta de Banco")]
        public decimal SaldoBanco { get; set; }

        [Required]
        [Display(Name = "Saldo en Libro Mayor de Banco")]
        public decimal SaldoLibro { get; set; }

        public decimal SaldoLibroInicial { get; set; }

        public List<ConciliacionLinea> ConciliacionLinea { get; set; }

    }
}

ERPMVC/Controllers/Contabilidad/ConciliacionController.cs
using ERPMVC.DTO;
using ERPMVC.Helpers;
using ERPMVC.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;


namespace ERPMVC.Controllers
{
    [Authorize]
    [CustomAuthorization]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class ConciliacionController : Controller
    {
        private readonly IOptions<MyConfig> config;
        private readonly ILogger _logger;
        private IHostingEnvironment _hostingEnvironment;
        private readonly ClaimsPrincipal _principal;
        public ConciliacionController(IHostingEnvironment hostingEnvironment
            , ILogger<ConciliacionController> logger, IOptions<MyConfig> config, IHttpContextAccessor httpContextAccessor)
        {
            this.config = config;
            this._logger = logger;
            _hostingEnvironment = hostingEnvironment;
            _principal = httpContextAccessor.HttpContext.User;
        }

        class objeto
        {
            public ConciliacionDTO[] arreglo { get; set; }

        }



        // GET: Conciliacion
        [Authorize(Policy = "Bancos.Conciliacion Bancaria")]
        public ActionResult Conciliacion()
        {
            ViewData["permisos"] = _principal;
            return View();
        }




        

        [HttpGet("[action]")]
        public async Task<DataSourceResult> GetConciliacion([DataSourceRequest]DataSourceRequest request)
        {
            List<ConciliacionDTO> _Conciliacion = new List<ConciliacionDTO>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/Conciliacion/GetConciliacionConCuenta");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _Conciliacion = JsonConvert.DeserializeObject<List<ConciliacionDTO>>(valorrespuesta);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }
            return _Conciliacion.ToDataSourceResult(request);

        }
        [HttpGet("[controller]/[action]")]

        public async Task<DataSourceResult> GetConciliacionLineaByConciliacionId([DataSourceRequest]DataSourceRequest request, Int64 ConciliacionId)
        {
            List<ConciliacionLinea> _ConciliacionLineas = new List<ConciliacionLinea>();

            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/ConciliacionLinea/GetConciliacionLineaByConciliacionId/" + ConciliacionId);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _ConciliacionLineas = JsonConvert.DeserializeObject<List<ConciliacionLinea>>(valorrespuesta);
                    
                }
                if (_ConciliacionLineas.Count == 0)
                {
                    Conciliacion _ConciliacionP = new Conciliacion();
                    
                        string baseadressP = config.Value.urlbase;
                        HttpClient _clientP = new HttpClient();
                        _clientP.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                        var resultP = await _client.GetAsync(baseadressP + "api/Conciliacion/GetConciliacionById/" + ConciliacionId);
                        string valorrespuestaP = "";
                        if (resultP.IsSuccessStatusCode)
                        {
                            valorrespuestaP = await (resultP.Content.ReadAsStringAsync());
                            _ConciliacionP = JsonConvert.DeserializeObject<Conciliacion>(valorrespuestaP);

                        }
                    string baseadressE = config.Value.urlbase;
                    HttpClient _clientE = new HttpClient();
                    _clientE.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                    var resultE = await _client.PostAsJsonAsync(baseadressE + "api/Conciliacion/GetJournalEntryByDateAccount",  _ConciliacionP);
                    string valorrespuestaE = "";
                    if (resultE.IsSuccessStatusCode)
                    {
                        valorrespuestaE = await (resultE.Content.ReadAsStringAsync());
                        _ConciliacionP.ConciliacionLinea = JsonConvert.DeserializeObject<List<ConciliacionLinea>>(valorrespuestaE);

                    }

                    _ConciliacionLineas = _ConciliacionP.ConciliacionLinea;
                }

            }
          catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }

            return (_ConciliacionLineas.ToDataSourceResult(request));
        }


        [HttpGet]
        public async Task<ActionResult> SFConciliacion(int id)
        {

            return await Task.Run(() => View(new Conciliacion {ConciliacionId = id }));



        }




        [HttpPost("[controller]/[action]")]
        public async Task<ActionResult> pvwAddConciliacion([FromBody]ConciliacionDTO _Conciliaciontp)
        {
            ConciliacionDTO _Conciliacion=null;
            List<MotivoConciliacion> motivos = new List<MotivoConciliacion>();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/Conciliacion/GetConciliacionById/" + _Conciliaciontp.ConciliacionId);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    if (!string.IsNullOrEmpty(valorrespuesta))
                    {
                        _Conciliacion = JsonConvert.DeserializeObject<ConciliacionDTO>(valorrespuesta);
                        _Conciliacion.Editar = _Conciliaciontp.Editar;
                    }
                }

                if (_Conciliacion == null)
                {
                    _Conciliacion = new ConciliacionDTO();
                    _Conciliacion.DateBeginReconciled = DateTime.Now;
                    _Conciliacion.DateEndReconciled = DateTime.Now;
                    _Conciliacion.FechaConciliacion = DateTime.Now;
                    _Conciliacion.Editar = 1;
                    _Conciliacion.EstadoId = 103;
                }

                
                result = await _client.GetAsync(baseadress + "api/MotivoConciliacion/GetMotivosConciliacion");
                valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    if (!string.IsNullOrEmpty(valorrespuesta))
                    {
                        motivos = JsonConvert.DeserializeObject<List<MotivoConciliacion>>(valorrespuesta);
                    }
                }

            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            ViewData["motivos"] = motivos;
            return PartialView(_Conciliacion);

        }

        public async Task<ActionResult> DetailsConciliation(Int64 ConciliacionId)
        {
            Conciliacion _ConciliacionP = new Conciliacion();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/Conciliacion/GetConciliacionById/" + ConciliacionId);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await(result.Content.ReadAsStringAsync());
                    _ConciliacionP = JsonConvert.DeserializeObject<Conciliacion>(valorrespuesta);

                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }



            return await Task.Run(() => View(_ConciliacionP));

            
        }
        public ActionResult Result()
        {
            return View();
        }
        public async Task<JsonResult> GetCheckAccountByAccountNumber(string AccountNumber)
        {
            CheckAccount _CheckAccountP = new CheckAccount();
            try

ERPMVC/Views/Conciliacion/Conciliacion.cshtml
@using Kendo.Mvc.UI
@using System.Security.Claims

@{ 
    ClaimsPrincipal permisos = (ClaimsPrincipal)ViewData["permisos"];
    ViewData["Title"] = "Conciliacion Bancaria";
}

<h3 class="text-themecolor">Conciliación Bancaria</h3>
<kendo-grid name="grdConciliaciones" height="500">
    <datasource type="DataSourceTagHelperType.WebApi" server-operation="true">
        <sorts>
            <sort field="ConciliacionId" direction="desc"/>

        </sorts>
        <transport>
            <read url="@Url.Action("GetConciliacion","Conciliacion")" />
        </transport>
        <schema>
            <model id="ConciliacionId">
                <fields>
                    <field name="ConciliacionId" type="number" />
                    <field name="FechaConciliacion" type="date" />
                    <field name="DateBeginReconciled" type="date" />
                    <field name="DateEndReconciled" type="date" />
                    <field name="SaldoConciliado" type="number" />
                    <field name="SaldoBanco" type="number" />
                    <field name="SaldoLibro" type="number" />
                </fields>
            </model>
        </schema>
    </datasource>
    <columns>
        @if (permisos.HasClaim("Bancos.Conciliacion Bancaria.Editar", "true") || permisos.HasClaim("Bancos.Conciliacion Bancaria.Ver Detalle", "true"))
        {
            <column width="100">
                <commands>
                    @if (User.HasClaim("Bancos.Conciliacion Bancaria.Editar", "true"))
                    {
                        <column-command name="EditarConciliacion" permiso="Bancos.Conciliacion Bancaria.Editar" text=" " icon-class="fa fa-edit" click="EditarConciliacion"></column-command>
                    }
                    @if (User.HasClaim("Bancos.Conciliacion Bancaria.Imprimir", "true"))
                    {
                        <column-command name="Imprimir" permiso="Bancos.Conciliacion Bancaria.Imprimir" text=" " icon-class="fa fa-print" click="Imprimir"></column-command>
                    }



                </commands>
            </column>
        }
        <column title="No." field="ConciliacionId" width="100"></column>
        <column title="Banco" field="BankName" width="200"></column>
        <column title="Cuenta" field="NombreCuenta" width="250"></column>
        <column title="Fecha Conciliación" field="FechaConciliacion" format="{0:dd/MM/yyyy}" width="200" />
        <column title="Desde" field="DateBeginReconciled" format="{0:dd/MM/yyyy}" width="200" />
        <column title="Hasta" field="DateEndReconciled" format="{0:dd/MM/yyyy}" width="200" />
        <column title="Saldo Conciliado" field="SaldoConciliado" template="<span style='float:right'>#= kendo.toString(SaldoConciliado,'n2') #</span>" width="200" />
        <column title="Saldo Banco" field="SaldoBanco" template="<span style='float:right'>#= kendo.toString(SaldoBanco,'n2') #</span>" width="200" />
        <column title="Saldo Libro" field="SaldoLibro" template="<span style='float:right'>#= kendo.toString(SaldoLibro,'n2') #</span>" width="200" />
        <column title="Estado" field="Estado" width="200"></column>
    </columns>
    <filterable>
        <messages clear="Limpiar" cancel="Cancelar" filter="Filtrar" info="Mostrar filas con un valor que:" />
        <operators>
            <string contains="Contiene" doesnotcontain="No contiene" endswith="Termina con" eq="Es igual a" neq="No es igual a" isnull="Es nulo" startswith="Inicia con" />
            <number eq="Es igual a" neq="No es igual a" gt="Es mayor que" gte="Es mayor o igual que" lt="Es menor que" lte="Es menor o igual que" isnull="Es nulo" />
            <date eq="Es igual que" neq="No es igual a" gt="Es mayor que" gte="Es mayor o igual que" lt="Es menor que" lte="Es menor o igual que" isnull="Es nulo" />
        </operators>
    </filterable>
    <toolbar>
        @if (permisos.HasClaim("Bancos.Conciliacion Bancaria.Agregar", "true"))
        {

            <toolbar-button template="PlantillaAgregar" />
        }
        <toolbar-button name="pdf" text="PDF" icon-class="k-icon k-i-pdf" />
        <toolbar-button name="excel" text="Excel" icon-class="k-icon k-i-excel" />
    </toolbar>
    <pdf file-name="Reporte_Conciliacion_@(DateTime.Now.ToString("yyyy_MM_dd_hh_mm_ss")).pdf" proxy-url="@Url.Action("Export","Home")" all-pages="true" />
    <excel file-name="Reporte_Conciliacion_@(DateTime.Now.ToString("yyyy_MM_dd_hh_mm_ss")).xlsx" filterable="true" proxy-url="@Url.Action("Export","Home")" all-pages="true" />
    <editable enabled="false" />
    <scrollable enabled="true" />
    <sortable enabled="true" />
</kendo-grid>

<div id="ModalConciliacion">
    @*@await Html.PartialAsync("pvwAddConciliacion", new ERPMVC.DTO.ConciliacionDTO { ConciliacionId = 0, Editar=0 })*@
</div>

<script>
    function EditarConciliacion(e) {
        e.preventDefault();
        var registro = this.dataItem($(e.currentTarget).closest('tr'));
        var parametros = {
            ConciliacionId: registro.ConciliacionId,
            Editar: 1
        };
        $.ajax({
            url: '@Url.Action("pvwAddConciliacion", "Conciliacion")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(parametros),
            success: function (result) {
                $("#ModalConciliacion").html('');
                $("#ModalConciliacion").html(result);
                $('#myModalConciliacionUpload').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }


    function Imprimir(e) {
        e.preventDefault();
        var registro = this.dataItem($(e.currentTarget).closest('tr'));
        var parametros = {
            ConciliacionId: registro.ConciliacionId
        };
        window.location.href = '@Url.Action("SFConciliacion", "Conciliacion")/' + registro.ConciliacionId;
        
    }

    function VerDetalleConciliacion(e) {
        e.preventDefault();
        var registro = this.dataItem($(e.currentTarget).closest('tr'));
        var parametros = {
            ConciliacionId: registro.ConciliacionId
        };
        $.ajax({
            url: '@Url.Action("pvwAddConciliacion", "Conciliacion")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(parametros),
            success: function (result) {
                $("#ModalConciliacion").html('');
                $("#ModalConciliacion").html(result);
                $('#myModalConciliacionUpload').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }

    function PlantillaAgregar(e) {
        var plantilla =
            '<a role="button" class="k-button k-button-icontext k-grid-Agregar" href="#" onclick="AgregarConciliacion()"><span class="k-icon k-i-plus"></span> Agregar</a>';
        return plantilla;
    }

    function AgregarConciliacion() {
        var parametros = {
            ConciliacionId: 0,
            Editar : 1
        };

        $.ajax({
            url: '@Url.Action("pvwAddConciliacion", "Conciliacion")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(parametros),
            success: function (result) {
                $("#ModalConciliacion").html('');
                $("#ModalConciliacion").html(result);
                $('#myModalConciliacionUpload').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }

    function RefreshConciliacion() {
        $("#grdConciliaciones").getKendoGrid().dataSource.read();
    }
</script>

ERPMVC/Views/Conciliacion/SFConciliacion.cshtml
@model ERPMVC.Models.Conciliacion
@{
    ViewData["Title"] = "Conciliacion";
 }

@using Syncfusion.JavaScript

<div style=" align-items:center; height:825px;width: 100%;">
    <ej-report-viewer id="reportviewer1" rendering-begin="renderingBegin" report-print="onPrintReport" processing-mode="Remote" locale="es-ES"
report-service-url="/ReportViewer"  report-loaded="onReportLoaded" report-path="/ReportsTemplate/Conciliacion.rdl" />

</div>




<script type="text/javascript">

    


    function onReportLoaded(sender) {

        var reportObj = $('#reportviewer1').data("ejReportViewer");

        //console.log('Llega al ReportLoaded');
        reportObj.model.parameters = [{
            name: 'ConciliacionId',
            labels: ['@Model.ConciliacionId'],
            values: ['@Model.ConciliacionId'],
            nullable: false
        }
        ];
    }


</script>


<ej-script-manager></ej-script-manager>