ERPMVC/Models/Catalogos/State.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ERPMVC.Models
{
    [DisplayColumn("Name")]
    public partial class State
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Id")]
        public long Id { get; set; } // bigint
        [Display(Name = "Departamento")]
        public string Name { get; set; } // text


        [Display(Name = "Usuario de creación")]
        public string Usuariocreacion { get; set; }

        [Display(Name = "Usuario de modificación")]
        public string Usuariomodificacion { get; set; }

        [Display(Name = "Fecha de creación")]
        public DateTime? FechaCreacion { get; set; }
        [Display(Name = "Fecha de modificación")]
        public DateTime? FechaModificacion { get; set; }

        [Display(Name = "Estado")]
        [DefaultValue(1)]
        public Int64 IdEstado { get; set; } = 1;

        public Int64 CountryId { get; set; }

        public List<City> City { get; set; }
    }
}

ERPMVC/Controllers/Catalogos/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ERPMVC.Helpers;
using ERPMVC.Models;
using ERPMVC.DTO;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Security.Claims;

namespace ERPMVC.Controllers
{
    [Authorize]
    [CustomAuthorization]
    public class StateController : Controller
    {
        private readonly IOptions<MyConfig> config;
        private readonly ILogger _logger;
        private readonly ClaimsPrincipal _principal;
        public StateController(ILogger<StateController> logger, IOptions<MyConfig> config, IHttpContextAccessor httpContextAccessor)
        {
            this.config = config;
            this._logger = logger;
            _principal = httpContextAccessor.HttpContext.User;
        }

        [Authorize(Policy = "Configuracion.Depto")]
        public async Task<IActionResult> State()
        {
            ViewData["Pais"] = await ObtenerPais();
            ViewData["permisoAgregar"] = _principal.HasClaim("Configuracion.Depto.Agregar", "true");
            ViewData["permisoEditar"] = _principal.HasClaim("Configuracion.Depto.Editar", "true");
            ViewData["permisoEliminar"] = _principal.HasClaim("Configuracion.Depto.Eliminar", "true");
            ViewData["permisoExportar"] = _principal.HasClaim("Configuracion.Depto.Exportar", "true");
            return View();
        }

        [HttpPost("[action]")]
        public async Task<ActionResult> pvwAddState([FromBody]StateDTO _sarpara)
        {
            StateDTO _State = new StateDTO();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/State/GetStateById/" + _sarpara.Id);
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<StateDTO>(valorrespuesta);

                }

                if (_State == null)
                {
                    _State = new StateDTO();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }



            return PartialView(_State);

        }



        async Task<IEnumerable<Country>> ObtenerPais()
        {
            IEnumerable<Country> paises = null;
            
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();

                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/Country/GetCountry");                
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    paises = JsonConvert.DeserializeObject<IEnumerable<Country>>(valorrespuesta);

                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }
            ViewData["Pais"] = paises.FirstOrDefault();
            return paises;

        }




        [HttpGet]
        public async Task<DataSourceResult> Get([DataSourceRequest]DataSourceRequest request)
        {
            List<State> _State = new List<State>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/State/GetState");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<List<State>>(valorrespuesta);
                    _State = _State.OrderByDescending(e => e.Id).ToList();
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return _State.ToDataSourceResult(request);

        }


        [HttpGet]
        public async Task<DataSourceResult> GetActivos([DataSourceRequest] DataSourceRequest request)
        {
            List<State> _State = new List<State>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/State/GetState");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<List<State>>(valorrespuesta).Where(w=> w.IdEstado==1).OrderByDescending(e => e.Id).ToList();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }
            return _State.ToDataSourceResult(request);
        }


        [HttpGet]
        public async Task<JsonResult> GetJson([DataSourceRequest]DataSourceRequest request,Int64 CountryId)
        {
            List<State> _State = new List<State>();
            try
            {

                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/State/GetState");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<List<State>>(valorrespuesta);
                    _State= _State.Where(q => q.CountryId == CountryId).OrderBy(q => q.Name).ToList();
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }


            return Json(_State.ToDataSourceResult(request));
        }


        [HttpGet]
        public async Task<JsonResult> GetJsonActivos([DataSourceRequest] DataSourceRequest request, Int64 CountryId)
        {
            List<State> _State = new List<State>();
            try
            {
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.GetAsync(baseadress + "api/State/GetState");
                string valorrespuesta = "";
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<List<State>>(valorrespuesta).Where(w => w.IdEstado==1).ToList();
                    _State = _State.Where(q => q.CountryId == CountryId).OrderBy(q => q.Name).ToList();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Ocurrio un error: { ex.ToString() }");
                throw ex;
            }
            return Json(_State.ToDataSourceResult(request));
        }


        [HttpPost]
        public async Task<ActionResult<State>> SaveState([FromBody]StateDTO _StateS)
        {

            State _State = _StateS;
            try
            {
                // DTO_NumeracionSAR _liNumeracionSAR = new DTO_NumeracionSAR();
                string baseadress = config.Value.urlbase;
                HttpClient _client = new HttpClient();
                _client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.Session.GetString("token"));
                var result = await _client.PostAsJsonAsync(baseadress + "api/State/GetStateByName" , _State);
                string valorrespuesta = "";
                _State.FechaModificacion = DateTime.Now;
                _State.Usuariomodificacion = HttpContext.Session.GetString("user");
                if (result.IsSuccessStatusCode)
                {
                    valorrespuesta = await (result.Content.ReadAsStringAsync());
                    _State = JsonConvert.DeserializeObject<StateDTO>(valorrespuesta);
                }

                if (_State == null) { _State = new Models.State(); }





                if (_State.Id > 0)
                {
                    if (_State.Id != _StateS.Id)
                        return await Task.Run(() => BadRequest($"Ya éxiste un departamento registrado con este nombre para este país."));
                }

ERPMVC/Views/State/State.cshtml
@using Kendo.Mvc.UI
@using ERPMVC.Models

@{
    ViewData["Title"] = "Departamento";
    var Pais = ViewData["Pais"] as IEnumerable<ERPMVC.Models.Country>;
    bool permisoAgregar, permisoEditar, permisoEliminar, permisoExportar;
    permisoAgregar = (bool)ViewData["permisoAgregar"];
    permisoEditar = (bool)ViewData["permisoEditar"];
    permisoEliminar = (bool)ViewData["permisoEliminar"];

}

<script>

    function onsave(e) {
        //   console.log(new Date(e.model.FechaRecepcion).toISOString());
        // e.model.set('FechaRecepcion', new Date(e.model.FechaRecepcion).toISOString());
    }

    function caidata(data) {
        data.FechaRecepcion = data.FechaRecepcion.toISOString('yyyy-MM-dd');
        data.FechaLimiteEmision = data.FechaLimiteEmision.toISOString('yyyy-MM-dd');
    }

    function AddState() {

        $('#ModalState').find(':input').not(':submit').val('');
        $('#ModalState').modal('show');
        $("#StateId").val('0');
        $("#Id").val('0');
        $("#CountryId").data("kendoDropDownList").value(0);
        var validator = $("#frmState").data("kendoValidator");
        validator.hideMessages();
        $('#ModalState').find(':input').not(':submit').val('');
        $("#CountryId").data("kendoDropDownList").value(0);

    }


    function EditState(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var dataObject = {
            Id: dataItem.Id,
            editar: 0
        };



        $.ajax({
            url: '@Url.Action("pvwAddState", "State")',
            method: 'POST',
            datatype: "json",
            contentType: 'application/json',
            async: false,
            data: JSON.stringify(dataObject),
            success: function (result) {
                $("#numState").html('');
                $("#numState").html(result);


                $('#ModalState').modal('show');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus + ": " + XMLHttpRequest.responseText);
            }
        });
    }

    function DeleteState(e) {
        if (confirm('¿Esta seguro que desea eliminar este registro?')) {
            e.preventDefault();
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            var dataObject = {
                Id: dataItem.Id,
                CountryId: dataItem.CountryId,
                editar: 0
            };
            $.ajax({
                url: '@Url.Action("Delete", "State")',
                method: 'POST',
                datatype: "json",
                contentType: 'application/json',
                async: false,
                data: JSON.stringify(dataObject),
                success: function (result) {
                    RefrescarGrid();
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    if (XMLHttpRequest.responseText == "No se puede eliminar este registro porque está siendo utilizado.") {
                        $.toast({
                            heading: 'Validación',
                            text: "No se puede eliminar este registro porque está siendo utilizado.",
                            position: 'top-right',
                            loaderBg: '#ff6849',
                            icon: 'error',
                            hideAfter: 30000,
                            stack: 6
                        });
                    }
                    else {
                        $.toast({
                            heading: 'Error',
                            text: textStatus + ": " + XMLHttpRequest.responseText,
                            position: 'top-right',
                            loaderBg: '#ff6849',
                            icon: 'error',
                            hideAfter: 30000,
                            stack: 6
                        });
                    }
                }
            });
        }
    }
    function RefrescarGrid() {
        var grid = $("#gridState").getKendoGrid();
        grid.dataSource.read();
    }


</script>

<h3 class="text-themecolor">Departamento</h3>

@(Html.Kendo().Grid<ERPMVC.Models.State>
            ()

            .Name("gridState")

            .Columns(columns =>
            {
                if (permisoEditar == true || permisoEliminar == true)
                {
                    columns.Command(command =>
                    {
                        //command.Custom("Ver detalles").Click("Detalles");
                        if (permisoEditar)
                        {
                            command.Custom("Editar").Text(" ").Click("EditState").IconClass("fa fa-edit");
                        }
                        if (permisoEliminar)
                        {
                            command.Custom("Eliminar").Text(" ").Click("DeleteState").IconClass("fa fa-trash-alt");
                        }

                    }).Width(170).Title("Acciones");
                }
                columns.Bound(p => p.Id).Width(150);
                columns.Bound(p => p.Name).Width(170);
                columns.ForeignKey(p => p.CountryId, (System.Collections.IEnumerable)ViewData["Pais"], "Id", "Name").Title("País").Width(200);
                columns.Bound(b => b.IdEstado).Width(150).ClientTemplate("#= IdEstado ==1 ? 'Activo' : 'Inactivo' #");

            })


            .ToolBar(tools =>
            {

                //tools.Create();
                if (permisoAgregar)
                {
                    tools.Custom().Text("Agregar").IconClass("k-icon k-i-plus")
                                                .HtmlAttributes(new { @class = "k-i-plus-sm", onclick = "AddState()" });
                }
                    tools.Excel().Text("Exportar a excel").HtmlAttributes(new { @class = "toolbar-field" });
                    tools.Pdf().Text("Exportar a pdf").HtmlAttributes(new { @class = "toolbar-field" });
            })
            .Editable(e => e.Mode(GridEditMode.PopUp).ConfirmDelete("¿Esta seguro que desea eliminar este registro?"))
            .Sortable()
            .Pageable(p => p.Refresh(true))
            .Filterable()
            .Scrollable()
            .Pdf(pdf => pdf.FileName("StateReport" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".pdf")
            .ProxyURL(Url.Action("Export", "Home")).AllPages())
            .Excel(excel => excel.FileName("StateReport_" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_"
            + DateTime.Now.Day + "_" + DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Second + ".xlsx").Filterable(true)
            .ProxyURL(Url.Action("Export", "Home")).AllPages(true))
            .DataSource(dataSource =>
            dataSource
            .WebApi()

            .ServerOperation(true)
            .Model(model =>
            {
                model.Id(p => p.Id);
                model.Field(p => p.Id).Editable(false);
                model.Field(p => p.CountryId).Editable(false);
                //model.Field(p => p.Country.Name).Editable(false);


            })
            .Events(events => events.Error("error_handler"))
            .Read(read => read.Action("Get", "State"))
            .Create(create => create.Action("Insert", "State").Type(HttpVerbs.Post))
            .Update(update => update.Action("Update", "State").Type(HttpVerbs.Post))
            //.Destroy(destroy => destroy.Action("Delete", "State").Type(HttpVerbs.Post))

            )
            .Events(e =>
            {
                e.Save("onsave");

            })
)

<div id="numState">
    @await Html.PartialAsync("pvwAddState", new ERPMVC.DTO.StateDTO { Id = 0 })
</div>



<script>
    function setToolbarTooltip(btn_cl, btn_tooltip) {
        $("#gridState").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    function setRowButtonTooltip(btn_cl, btn_tooltip) {
        $("#gridState").kendoTooltip({
            filter: btn_cl,
            content: btn_tooltip
        });
    }

    setToolbarTooltip(".k-grid-Agregar", "Agregar nuevo registro");
    setRowButtonTooltip(".k-grid-Eliminar", "Eliminar registro");
    setRowButtonTooltip(".k-grid-Editar", "Editar registro");
</script>

ERPMVC/Views/State/pvwAddState.cshtml
@model ERPMVC.DTO.StateDTO

@{ Layout = null;
    var messages = new Dictionary<string, string>() { { "custom", "Ingrese un valor correcto." },
   // {"required","Valor requerido" }
};
    var rules = new Dictionary<string, string>() { { "custom", "customFunction" } };
}


<div id="ModalState" class="modal fade" role="dialog">
    <!-- Modal content-->
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Departamento</h4>
                <button type="button" name="btnprueba" class="close" data-dismiss="modal">&times;</button>                
            </div>
            <div class="modal-body">
                <div class="row" id="validation">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form id="frmState" kendo-validator="true"
                                      data-ajax="true"
                                      data-ajax-method="post"
                                      data-ajax-begin="SaveState"
                                      class="validation-wizard wizard-circle">
                                    <div class="form-body">
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label asp-for="Id" class=" control-label" style="width:100%">Id Departamento</label>
                                                    <input type="text" asp-for="Id" name="Id" class="form-control" disabled="disabled" style="min-width:100%" />
                                                    <span asp-validation-for="Id" class="text-danger"></span>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label asp-for="Name" class=" control-label" style="width:100%">Nombre Departamento</label>
                                                    <input type="text" asp-for="Name" name="Description" class="form-control" required data-required-msg="La descripción es requerida." autocomplete="off" style="min-width:100%" onkeypress="return SoloLetras(event)" />
                                                    <span asp-validation-for="Name" class="text-danger"></span>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label asp-for="CountryId" class="control-label">País</label>
                                                    <kendo-dropdownlist name="CountryId"
                                                                        required data-required-msg="El país es requerido."
                                                                        for="@Model.CountryId"
                                                                        filter="Kendo.Mvc.UI.FilterType.Contains"
                                                                        option-label="Seleccionar País"
                                                                        datatextfield="Name"
                                                                        datavaluefield="Id"
                                                                        style="width: 100%;">
                                                        <datasource type="DataSourceTagHelperType.WebApi" server-operation="true">
                                                            <transport>
                                                                <read url="@Url.Action("Get", "Country")" />
                                                            </transport>
                                                        </datasource>
                                                    </kendo-dropdownlist>
                                                    <span asp-validation-for="CountryId" class="text-danger"></span>
                                                </div>
                                            </div>

                                            
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label asp-for="IdEstado" class="control-label"></label>
                                                    <kendo-dropdownlist name="IdEstado"
                                                                        required data-required-msg="Debe selecccionar un estado"
                                                                        for="@Model.IdEstado"
                                                                        filter="Kendo.Mvc.UI.FilterType.Contains"
                                                                        option-label="Seleccionar un estado"
                                                                        datatextfield="NombreEstado"
                                                                        datavaluefield="IdEstado"
                                                                        style="width: 100%;">
                                                        <datasource type="DataSourceTagHelperType.WebApi" server-operation="true">
                                                            <transport>
                                                               <read url="@Url.Action("GetGrupoEstadoUno", "Estados")" />
                                                            </transport>
                                                        </datasource>
                                                    </kendo-dropdownlist>
                                                    <span asp-validation-for="IdEstado" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <button id="btnState" class="form-control btn-miboton" type="submit"> Guardar </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    //Validaciones
    function SoloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }

    $(document).ready(function () {
        $("input").on("keyup", function () {
            s = this.selectionStart;
            e = this.selectionEnd;
            a = this.value.split(" "), b = "";
            for (n in a) {
                b += " " + a[n].substr(0, 1).toUpperCase() + a[n].substr(1).toLowerCase();
            }
            this.value = b.substr(1);
            this.selectionStart = s;
            this.selectionEnd = e;
        });
    });

    function RefrescarGrid() {
        var grid = $("#gridState").getKendoGrid();
        grid.dataSource.read();
    }
        function SaveState(e) {

            var notification = $("#notification").data("kendoNotification");
           // e.preventDefault();
            $("#btnState").hide();
            $("#btnState").prop("disabled", true);

            var displayedData = $("#gridState").data().kendoGrid.dataSource.view();

            var dataObject = {
                'Id': $("#Id").val() === "" ? "0" : $("#Id").val(),
                'Name': $("#Name").val(),
                'CountryId': $("#CountryId").val(),
                'IdEstado': $("#IdEstado").val()
            };

            console.log(dataObject)


            var validator = $("#frmState").data("kendoValidator");
                 var status = $(".status");


                if (validator.validate()) {

                    $.ajax({
                        url: '@Url.Action("SaveState", "State")',
                        method: 'POST',
                        datatype: "json",
                        contentType: 'application/json',
                        async: false,
                        data: JSON.stringify(dataObject),
                        success: function (data) {

                            //notification.show({
                            //    message: "Guardado correctamente!"
                            //}, "upload-success");
                            $.toast({
                                heading: 'Satisfactorio',
                                text: 'Datos guardados correctamente.',
                                position: 'top-right',
                                loaderBg: '#ff6849',
                                icon: 'success',
                                hideAfter: 5000,
                                stack: 6
                            });

                            RefrescarGrid();

                            $('#ModalState').modal('hide');


                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                        //    console.log('VERIFICAR')

                            notification.show({
                                title: "Validacion",
                                message: textStatus + ": " + XMLHttpRequest.responseText
                            }, "error");

                        }
                    });

                }
                else {
                    notification.show({
                        title: "Validacion",
                        message: "Datos invalidos en el formulario!"
                    }, "error");
                }


            $("#btnState").show();
            $("#btnState").prop("disabled", false);
    }
</script>